name: CI - Run Tests

on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install backend dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run backend tests
        working-directory: backend
        run: pytest
        
      - name: List files in frontend directory
        working-directory: frontend
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing files in src directory:"
          ls -R src
          echo "Full frontend directory listing:"
          ls -R . # You can also use `find . -print` for a different format

      - name: Run frontend tests
        working-directory: frontend
        run: npm test
